const functions = require("firebase-functions");
const admin = require("firebase-admin");
if (admin.apps.length === 0) admin.initializeApp();
exports.createUser = functions.https.onCall(async (data, context) => {
  try {
    // add a login document (autogenerated id)
    //if (admin.apps.length === 0) admin.initializeApp();
    await admin.firestore().collection("users").doc(data.uid).set({
      name: data.name,
      creationDate: admin.firestore.FieldValue.serverTimestamp(),
      darkMode: data.darkMode,
      language: data.language,
      userProjects: [],
    });

    return {
      errorCode: 0,
      userData: {},
    };
  } catch (e) {
    return {
      errorCode: 1,
      errorMessage: e.toString(),
    };
  }
});
